In [1]:
import numpy as np

#tablice
a = np.array([1,2,3,4,5,6,7])
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

bt = np.transpose(b)

arr = np.arange(100)

arr1 = np.linspace(0,2,10)

arr2 = np.arange(0,101,5)

print(a)
print(b)
print(bt)
print(arr)
print(arr1)
print(arr2)


#liczby losowe
ra = np.round(np.random.random(20),2)
rb = np.random.randint(100)


ma = np.zeros((3,2))
mb = np.ones((3,2))

mc = np.random.randint(0,100,(5,5),dtype=np.int32)

rc = np.round((np.random.random(10)),2)

print(ra)
print(rb)
print(ma)
print(mb)
print(mc)
print(rc)



#sekcja danych
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.int32)
print(b.ndim)
print(b.size)


print(b[0][1])
print(b[0][3])

print(b[0][0])
print(b[0])

c = np.random.randint(0,101,(20,7))
print(c[::5])


#operacje matematyczne i logiczne

a = np.random.randint(0,11,(3,3))
b = np.random.randint(0,11,(3,3)) 

add = a + b
mul = np.matmul(a,b)
div = np.dot(a,np.linalg.inv(b))
pow = np.power(a,b)

con1 = a >= 4
con2 = (a >= 1) & (a <= 4)

sum = np.trace(b)

print(a)
print(b)
print(add)
print(mul)
print(div)
print(pow)
print(con1)
print(con2)
print(sum)



#dane statystyczne

sum_b = np.sum(b)
min_b = np.min(b)
std_b = np.std(b)
max_b = np.max(b)

rows_b = np.mean(b, axis=1)
cols_b = np.mean(b, axis=0)

print(sum_b)
print(min_b)
print(std_b)
print(max_b)
print(rows_b)
print(cols_b)



#rzutowanie wymiarow

tab = np.random.random(50)

m1 = tab.reshape(10,5)
m2 = tab.resize(10,5)


test = tab.ravel()

tab1 = np.array([1,2,3,4,5])
tab2 = np.array([1,2,3,4])

tab2 = tab2[:, np.newaxis]
res = np.add(tab1,tab2)

print(tab)
print(m1)
print(m2)
print(test)
print(tab1)
print(tab2)
print(res)



#sortowanie danych

a = np.random.randn(5,5)

sort1 = np.sort(a, axis = 1)
sort2 = np.sort(a, axis = 0)


b = np.array([
(1,'MZ','mazowieckie'),
(2,'ZP','zachodniopomorskie'),
(3,'ML','małopolskie')])

matrixb = b.reshape(3,3)
sort3 = matrixb[matrixb[:,1].argsort()]

print(a)
print(sort1)
print(sort2)

print(b)
print(matrixb)
print(sort3)
print(b[b[:, 1] == 'ZP'][0, 2])


[1 2 3 4 5 6 7]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
[0.83 0.61 0.08 0.18 0.63 0.98 0.22 0.66 0.65 0.01 0.96 0.96 0.79 0.48
 0.76 0.25 0.4  0.14 0.31 0.  ]
91
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[33 53 65 65 63]
 [36 19 79 95 22]
 [18 37 93  6 41]
 [ 5 35 99 15 70]
 [ 3  6  0 59  5]]
[0.47 0.67 0.23 0.05 0.55 0.84 0.46 0.79 0.25 0.46]
2
10
2
4
1
[1 2 3 4 5]
[[94 84 95 21 14 77 64]
 [ 6 52 98 17 31 66 73]
 [ 8 38 90 30 85  6

In [10]:

import numpy as np

a = np.random.random(5)

print(a)

[0.62797311 0.41851836 0.8589443  0.33930717 0.78924686]


In [11]:
import numpy as np
#ZAD1

matrix = np.random.randint(1,100,(10,5))
trace = np.trace(matrix[:5,:5])
values = np.diag(matrix[:5,:5])

print(matrix)
print(trace)
print(values)

print('#########################')
print("ZAD 2")

#ZAD2
arr1 = np.random.randn(6)
arr2 = np.random.randn(6)
res = arr1 * arr2

print(arr1)
print(arr2)
print(res)

[[50 85 17 34 20]
 [15  5 15 20 69]
 [92  4 61 94 87]
 [36 51 17 14 89]
 [36 86 68 44 40]
 [82 47 45 69 96]
 [61 94 74 23 40]
 [28 38 29 57 67]
 [61 71 48 44  9]
 [78 21 46  3 29]]
170
[50  5 61 14 40]
#########################
ZAD 2
[ 1.33331642 -0.59973556  0.12588449  0.66757971 -1.30089504  0.18922319]
[-1.78875006 -1.24664808 -1.07135257 -1.09948503 -1.12053917  0.89150101]
[-2.38496982  0.74765918 -0.13486668 -0.7339939   1.45770386  0.16869266]


In [4]:
import numpy as np

#ZAD 3

arr1 = np.random.randint(1,101, size = 20)
arr2 = np.random.randint(1,101, size = 20)

mat1 = arr1.reshape(4,5)
mat2 = arr2.reshape(4,5)

res = mat1 + mat2

print(arr1)
print(arr2)
print(mat1)
print(mat2)
print(res)


print('#########################')
print("ZAD 4")

#ZAD 4

mat3 = np.random.randint(1,101,(5,4))
mat4 = np.random.randint(1,101,(4,5))

mat4T = mat4.T 

res1 = mat3 + mat4T

print(mat3)
print(mat4)
print(res1)

print('#########################')
print("ZAD 5")

#ZAD 5

col3 = res1[:, 2]  # kolumna 3 
col4 = res1[:, 3]  # kolumna 4 

res2 = np.matmul(col3,col4)

print(col3)
print(col4)
print(res2)


[18 86 65 46 86 87 61  5 58 18 10 50 21  9 78 68 42 39  1 39]
[  4  91  96  15  13  82   2  19  64  49  60  36  98  38 100  28  12  59
  14  41]
[[18 86 65 46 86]
 [87 61  5 58 18]
 [10 50 21  9 78]
 [68 42 39  1 39]]
[[  4  91  96  15  13]
 [ 82   2  19  64  49]
 [ 60  36  98  38 100]
 [ 28  12  59  14  41]]
[[ 22 177 161  61  99]
 [169  63  24 122  67]
 [ 70  86 119  47 178]
 [ 96  54  98  15  80]]
#########################
ZAD 4
[[20 85 75 20]
 [63 73 58 89]
 [51 35 87 26]
 [62 23 79 81]
 [73 21 19 89]]
[[10 93 92 75 83]
 [18 41 53  9 15]
 [66 13 45  8 75]
 [63 91 50 78 14]]
[[ 30 103 141  83]
 [156 114  71 180]
 [143  88 132  76]
 [137  32  87 159]
 [156  36  94 103]]
#########################
ZAD 5
[141  71 132  87  94]
[ 83 180  76 159 103]
58030


In [5]:
import numpy as np

#zad 6

normal = np.random.normal(loc = 0, scale = 1, size = (1000,))
uniform = np.random.uniform(low = 0, high = 1, size = (1000,))

nmean = np.mean(normal) #srenia
nstd = np.std(normal) #odchylenie standardowe
nvar = np.var(normal) # wariancja

umean = np.mean(uniform)
ustd = np.std(uniform)
uvar = np.var(uniform)

print('normal')
print(nmean)
print(nstd)
print(nvar)

print('uniform')
print(umean)
print(ustd)
print(uvar)



normal
-0.008885869545058853
0.9980240325068238
0.9960519694611817
uniform
0.5035371507135854
0.28701216867561247
0.08237598496787821


In [6]:
#ZAD 7 

import numpy as np
from numpy.lib.stride_tricks import as_strided

a = np.random.randint(1,101,(3,3))
b = np.random.randint(1,101,(3,3)) 

res1 = a * b
res2 = np.dot(a,b)

print(a)
print(b)
print(res1)
print(res2)


# a * b to mnożenie elementow odpowiadających sobie w obu macierzach.
# np.dot(a, b) to mnozenie macierzy zgodne z definicja iloczynu macierzy.


print('#########################')
print("ZAD 8")


#ZAD 8

c = np.random.randint(1, 101, (6, 6))
d = as_strided(c, shape=(3, 5), strides = c.strides)

print(c)
print(c.strides)
print(d)



[[35 68 52]
 [50 95 36]
 [93 79 67]]
[[ 1 18 30]
 [18 35 81]
 [85  9 89]]
[[  35 1224 1560]
 [ 900 3325 2916]
 [7905  711 5963]]
[[ 5679  3478 11186]
 [ 4820  4549 12399]
 [ 7210  5042 15152]]
#########################
ZAD 8
[[64 58 98 98 81 87]
 [35 41  3 58 58 55]
 [13 66 48 64 75 96]
 [84 81 57 62 59 86]
 [69 18 43 13 30 25]
 [46 26 44  3 13 30]]
(24, 4)
[[64 58 98 98 81]
 [35 41  3 58 58]
 [13 66 48 64 75]]


In [7]:
import numpy as np

#ZAD 9  
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vstack = np.vstack((a, b))
hstack = np.hstack((a, b))

print(vstack)
print(hstack)

#vstack - gdy chcemy dodac nowe wiersze do macierzy
#hstack - gdy chcemy dodac nowe kolumny do macierzy

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [8]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

#ZAD 10

matrix = np.array([[0, 1, 2, 3, 4, 5],[6, 7, 8, 9, 10, 11],[12, 13, 14, 15, 16, 17],[18, 19, 20, 21, 22, 23]])
 
sshape = matrix.strides  
smatrix = as_strided(matrix, shape=(2, 2, 2, 3), strides=(sshape[0] * 2, sshape[1] * 3, sshape[0], sshape[1]))

max_values = np.max(smatrix, axis=(2, 3))


print(matrix)
print(smatrix)
print(max_values)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[[ 0  1  2]
   [ 6  7  8]]

  [[ 3  4  5]
   [ 9 10 11]]]


 [[[12 13 14]
   [18 19 20]]

  [[15 16 17]
   [21 22 23]]]]
[[ 8 11]
 [20 23]]
